# Datenstrom Yellow extension settings

Extension: MDForm
Version: 0.0.2
Description: Markdown Form Extension for Datenstrom Yellow
Developer: Andreas Staedler (goethe)
Tag: feature
DownloadUrl: https://github.com/goehte/yellow-mdform/archive/refs/tags/v0.0.2-alpha_bugfix1.zip
DocumentationUrl: https://github.com/goehte/yellow-mdform
Published: 2026-04-23 00:25:00
Status: experimental
system/workers/mdform.php: mdform.php, create, update
media/forms/form.mdf: test.mdf, create, update, careful
