# Datenstrom Yellow extension settings

Extension: MDForm
Version: 0.0.1
Description: Markdown Form Extension for Datenstrom Yellow
Developer: Andreas Staedler (goethe)
Tag: feature
DocumentationUrl: https://github.com/goehte/yellow-mdform
Published: 2026-04-14 00:50:00
Status: experimental
system/workers/mdform.php: mdform.php, create, update
media/forms/form.mdf: from.mdf, create, update, careful
